version: 1.2
workflows:
  - subclass: WDL
    name: make_guide_mutation_beds
    readMePath: /workflows/make_guide_mutation_beds/README.md
    primaryDescriptorPath: /workflows/make_guide_mutation_beds/make_guide_mutation_beds.wdl
    testParameterFiles:
      - /workflows/make_guide_mutation_beds/make_guide_mutation_beds.json
    filters:
      branches:
        - main
        - dev
    publish: True
  - subclass: WDL
    name: make_guide_mutation_beds
    readMePath: /workflows/make_guide_mutation_beds/README.md
    primaryDescriptorPath: /workflows/make_guide_mutation_beds/make_guide_mutation_beds.wdl
    testParameterFiles:
      - /workflows/make_guide_mutation_beds/make_guide_mutation_beds.json
    filters:
      branches:
        - main
        - dev
    publish: True
