[tool.poetry]
name = "omics-wgs-pipeline"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
packages = [{include = "omics_wgs_pipeline"}, {include = "gumbo_graphql_client"}]

[tool.poetry.dependencies]
python = "^3.12"
ariadne-codegen = "^0.13.0"
pandas = "^2.2.2"
pandera = "^0.19.0"
python-dotenv = "^1.0.1"
pydantic = "^2.7.1"
click = "^8.1.7"
google-cloud-storage = "^2.16.0"
firecloud = "^0.16.36"
google-cloud-logging = "^3.10.0"
functions-framework = "^3.5.0"
typer = "^0.9.0"
pyarrow = "^15.0.2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.2"
pyright = "^1.1.359"
ruff-lsp = "^0.0.53"

[[tool.poetry.source]]
name = "public-python"
url = "https://us-central1-python.pkg.dev/cds-artifacts/public-python/simple/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = [
    "I",  # isort formatting
]

[tool.pyright]
venvPath = "."
venv = ".venv"
include = ["omics_wgs_pipeline", "main.py"]
