mutation InsertTaskEntities(
  $username: String!
  $objects: [task_entity_insert_input!]!
) {
  set_username(args: { _username: $username }) {
    username
  }
  insert_task_entity(objects: $objects) {
    returning {
      id
      sequencing_id
    }
  }
}

query SequencingTaskEntities {
  records: task_entity(where: { sequencing_id: { _is_null: false } }) {
    id
    sequencing_id
  }
}
