[settings]
force_keep = [
    "center",
    "cgc_other_germline_mut",
    "cgc_other_syndrome/disease",
    "clinvar_vcf_clndisdbincl",
    "clinvar_vcf_clndnincl",
    "clinvar_vcf_clnsigconf",
    "clinvar_vcf_clnsigincl",
    "clinvar_vcf_dbvarid",
    "clinvar_vcf_filter",
    "clinvar_vcf_ssr",
    "contq",
    "cosmicfusion_fusion_id",
    "gencode_34_ncbibuild",
    "nalod",
    "nlod",
    "normal_barcode",
    "oc_base__note",
    "oc_brca1_func_assay__class",
    "oc_brca1_func_assay__score",
    "oc_cancer_hotspots__samples",
    "oc_hess_drivers__is_driver",
    "oc_hess_drivers__signature",
    "oc_oncokb__all",
    "oc_oncokb__highestdiagnosticimplicationlevel",
    "oc_oncokb_dm__all",
    "oc_oncokb_dm__highestdiagnosticimplicationlevel",
    "oc_oncokb_dm__highestprognosticimplicationlevel",
    "oc_oncokb_dm__highestresistancelevel",
    "oc_oncokb_dm__highestsensitivelevel",
    "oc_oncokb_dm__tumorsummary",
    "ocm",
    "seqq",
    "source",
    "strandq",
    "tumor_barcode",
]

compound_info_fields = [
    "ANN",
    "CSQ",
    "LOF",
    "NMD",
]

url_encoded_col_name_regexes = [
    "^info__civic_desc",
    "^info__clndn_3",
    "^info__csq__hgvsp",
    "^info__oc_base_achange",
    "^info__oc_base_all_mappings",
    "^info__oc_gwas_catalog_ci",
    "^info__oc_gwas_catalog_disease",
    "^info__oc_gwas_catalog_init_samp",
    "^info__oc_gwas_catalog_rep_samp",
    "^info__oc_pharmgkb_chemicals",
    "^info__oc_pharmgkb_drug_assoc",
    "^info__oc_pharmgkb_pheno_cat",
    "^info__oc_provean_all",
    "^info__oc_revel_all",
    "^info__oc_revel_transcript",
    "^info__oncokb_muteff",
    "^info__oncokb_onco",
]

info_cols_ignored = [
    "FUNCOTATION"
]

[settings.info_subfield_types.ANN]
"AA.pos / AA.length" = "VARCHAR"
"cDNA.pos / cDNA.length" = "VARCHAR"
"CDS.pos / CDS.length" = "VARCHAR"
"ERRORS / WARNINGS / INFO" = "VARCHAR"
"HGVS.c" = "VARCHAR"
"HGVS.p" = "VARCHAR"
Allele = "VARCHAR"
Annotation = "VARCHAR"
Annotation_Impact = "VARCHAR"
Distance = "VARCHAR"
Feature_ID = "VARCHAR"
Feature_Type = "VARCHAR"
Gene_ID = "VARCHAR"
Gene_Name = "VARCHAR"
Rank = "VARCHAR"
Transcript_BioType = "VARCHAR"

[settings.info_subfield_types.LOF]
Gene_ID = "VARCHAR"
Gene_Name = "VARCHAR"
Number_of_transcripts_in_gene = "VARCHAR"
Percent_of_transcripts_affected = "VARCHAR"

[settings.info_subfield_types.NMD]
Gene_ID = "VARCHAR"
Gene_Name = "VARCHAR"
Number_of_transcripts_in_gene = "VARCHAR"
Percent_of_transcripts_affected = "VARCHAR"

[settings.info_subfield_types.CSQ]
AF = "VARCHAR"
AFR_AF = "VARCHAR"
AMR_AF = "VARCHAR"
APPRIS = "VARCHAR"
Allele = "VARCHAR"
Amino_acids = "VARCHAR"
BIOTYPE = "VARCHAR"
CANONICAL = "VARCHAR"
CCDS = "VARCHAR"
CDS_position = "VARCHAR"
CLIN_SIG = "VARCHAR"
Codons = "VARCHAR"
Consequence = "VARCHAR"
DISTANCE = "VARCHAR"
DOMAINS = "VARCHAR"
EAS_AF = "VARCHAR"
ENSP = "VARCHAR"
EUR_AF = "VARCHAR"
EXON = "VARCHAR"
Existing_variation = "VARCHAR"
FLAGS = "VARCHAR"
Feature = "VARCHAR"
Feature_type = "VARCHAR"
GENE_PHENO = "VARCHAR"
Gene = "VARCHAR"
HGNC_ID = "VARCHAR"
HGVS_OFFSET = "VARCHAR"
HGVSc = "VARCHAR"
HGVSp = "VARCHAR"
HIGH_INF_POS = "VARCHAR"
IMPACT = "VARCHAR"
INTRON = "VARCHAR"
LoFtool = "VARCHAR"
MANE_PLUS_CLINICAL = "VARCHAR"
MANE_SELECT = "VARCHAR"
MAX_AF = "VARCHAR"
MAX_AF_POPS = "VARCHAR"
MOTIF_NAME = "VARCHAR"
MOTIF_POS = "VARCHAR"
MOTIF_SCORE_CHANGE = "VARCHAR"
PHENO = "VARCHAR"
PUBMED = "VARCHAR"
PolyPhen = "VARCHAR"
Protein_position = "VARCHAR"
SAS_AF = "VARCHAR"
SIFT = "VARCHAR"
SOMATIC = "VARCHAR"
STRAND = "VARCHAR"
SWISSPROT = "VARCHAR"
SYMBOL = "VARCHAR"
SYMBOL_SOURCE = "VARCHAR"
TRANSCRIPTION_FACTORS = "VARCHAR"
TREMBL = "VARCHAR"
TSL = "VARCHAR"
UNIPARC = "VARCHAR"
UNIPROT_ISOFORM = "VARCHAR"
VARIANT_CLASS = "VARCHAR"
am_class = "VARCHAR"
am_pathogenicity = "VARCHAR"
cDNA_position = "VARCHAR"
gnomADe_AF = "VARCHAR"
gnomADe_AFR_AF = "VARCHAR"
gnomADe_AMR_AF = "VARCHAR"
gnomADe_ASJ_AF = "VARCHAR"
gnomADe_EAS_AF = "VARCHAR"
gnomADe_FIN_AF = "VARCHAR"
gnomADe_NFE_AF = "VARCHAR"
gnomADe_OTH_AF = "VARCHAR"
gnomADe_SAS_AF = "VARCHAR"
gnomADg_AF = "VARCHAR"
gnomADg_AFR_AF = "VARCHAR"
gnomADg_AMI_AF = "VARCHAR"
gnomADg_AMR_AF = "VARCHAR"
gnomADg_ASJ_AF = "VARCHAR"
gnomADg_EAS_AF = "VARCHAR"
gnomADg_FIN_AF = "VARCHAR"
gnomADg_MID_AF = "VARCHAR"
gnomADg_NFE_AF = "VARCHAR"
gnomADg_OTH_AF = "VARCHAR"
gnomADg_SAS_AF = "VARCHAR"
miRNA = "VARCHAR"
pLI_gene_value = "VARCHAR"
