[settings]
force_keep = [
    "center",
    "cgc_other_germline_mut",
    "cgc_other_syndrome/disease",
    "clinvar_vcf_clndisdbincl",
    "clinvar_vcf_clndnincl",
    "clinvar_vcf_clnsigconf",
    "clinvar_vcf_clnsigincl",
    "clinvar_vcf_dbvarid",
    "clinvar_vcf_filter",
    "clinvar_vcf_ssr",
    "contq",
    "cosmicfusion_fusion_id",
    "gencode_34_ncbibuild",
    "nalod",
    "nlod",
    "normal_barcode",
    "oc_base__note",
    "oc_brca1_func_assay__class",
    "oc_brca1_func_assay__score",
    "oc_cancer_hotspots__samples",
    "oc_hess_drivers__is_driver",
    "oc_hess_drivers__signature",
    "oc_oncokb__all",
    "oc_oncokb__highestdiagnosticimplicationlevel",
    "oc_oncokb_dm__all",
    "oc_oncokb_dm__highestdiagnosticimplicationlevel",
    "oc_oncokb_dm__highestprognosticimplicationlevel",
    "oc_oncokb_dm__highestresistancelevel",
    "oc_oncokb_dm__highestsensitivelevel",
    "oc_oncokb_dm__tumorsummary",
    "ocm",
    "seqq",
    "source",
    "strandq",
    "tumor_barcode",
]

compound_info_fields = [
    "ANN",
    "CSQ",
    "LOF",
    "NMD",
]

url_encoded_col_name_regexes = [
    "^civic_desc$",
    "^clndn$",
    "^clnvi$",
    "^oc_",
    "^oncokb_muteff$",
    "^oncokb_oncogenic$",
]

info_cols_ignored = [
    "FUNCOTATION"
]
