[settings]
force_keep = [
    "center",
    "cgc_other_germline_mut",
    "cgc_other_syndrome/disease",
    "clinvar_vcf_clndisdbincl",
    "clinvar_vcf_clndnincl",
    "clinvar_vcf_clnsigconf",
    "clinvar_vcf_clnsigincl",
    "clinvar_vcf_dbvarid",
    "clinvar_vcf_filter",
    "clinvar_vcf_ssr",
    "contq",
    "cosmicfusion_fusion_id",
    "gencode_34_ncbibuild",
    "nalod",
    "nlod",
    "normal_barcode",
    "oc_base__note",
    "oc_brca1_func_assay__class",
    "oc_brca1_func_assay__score",
    "oc_cancer_hotspots__samples",
    "oc_hess_drivers__is_driver",
    "oc_hess_drivers__signature",
    "oc_oncokb__all",
    "oc_oncokb__highestdiagnosticimplicationlevel",
    "oc_oncokb_dm__all",
    "oc_oncokb_dm__highestdiagnosticimplicationlevel",
    "oc_oncokb_dm__highestprognosticimplicationlevel",
    "oc_oncokb_dm__highestresistancelevel",
    "oc_oncokb_dm__highestsensitivelevel",
    "oc_oncokb_dm__tumorsummary",
    "ocm",
    "seqq",
    "source",
    "strandq",
    "tumor_barcode",
]

compound_info_fields = [
    "ANN",
    "CSQ",
    "FUNCOTATION",
    "LOF",
    "NMD",
]

url_encoded_col_name_regexes = [
    "^info__civic_desc",
    "^info__clndn_3",
    "^info__csq__hgvsp",
    "^info__oc_base_achange",
    "^info__oc_base_all_mappings",
    "^info__oc_gwas_catalog_ci",
    "^info__oc_gwas_catalog_disease",
    "^info__oc_gwas_catalog_init_samp",
    "^info__oc_gwas_catalog_rep_samp",
    "^info__oc_pharmgkb_chemicals",
    "^info__oc_pharmgkb_drug_assoc",
    "^info__oc_pharmgkb_pheno_cat",
    "^info__oc_provean_all",
    "^info__oc_revel_all",
    "^info__oc_revel_transcript",
    "^info__oncokb_muteff",
    "^info__oncokb_onco",
]

funco_sanitized_col_name_regexes = ["^info__funcotation"]

bool_cols = [
    "info__csq__high_inf_pos",
    "info__funcotation__gnom_ad_genome_reverse_complemented_alleles",
    "info__funcotation__gnom_ad_genome_swapped_alleles",
    "info__rm",
    "info__segdup",
]

drop_cols = [
    "info__dp",
    "info__funcotation__clin_var_vcf_mc",
    "info__funcotation__gencode_34_chromosome",
    "info__funcotation__oreganno_build",
    "value__ad",
    "value__af",
    "value__f1r2",
    "value__f2r1",
    "value__fad",
    "value__gt",
    "value__pgt",
    "value__pid",
    "value__pl",
    "value__ps",
    "value__sb",
]
