from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
from google.api_core.exceptions import NotFound
from google.cloud import bigquery
from nebelung.terra_workspace import TerraWorkspace

pd.set_option("display.max_columns", 30)
pd.set_option("display.max_colwidth", 50)
pd.set_option("display.max_info_columns", 30)
pd.set_option("display.max_info_rows", 20)
pd.set_option("display.max_rows", 20)
pd.set_option("display.max_seq_items", None)
pd.set_option("display.width", 200)
pd.set_option("expand_frame_repr", True)
pd.set_option("mode.chained_assignment", "warn")

bq_client = bigquery.Client(project="depmap-omics")

ws = TerraWorkspace(
    workspace_namespace="broad-firecloud-ccle",
    workspace_name="depmap-omics-wgs-mut-dev",
)

samples = ws.get_entities("sample")

eval_samples = samples.loc[
    :,
    ["sample_id", "wgs_cn_full_annotated_parquet"],
]

eval_samples.set_index("sample_id", inplace=True)

schema = [
    {"name": "chrom", "type": "STRING", "mode": "NULLABLE"},
    {"name": "pos", "type": "INTEGER", "mode": "NULLABLE"},
    {"name": "ref", "type": "STRING", "mode": "NULLABLE"},
    {"name": "alt", "type": "STRING", "mode": "NULLABLE"},
    {"name": "civic_description", "type": "STRING", "mode": "NULLABLE"},
    {"name": "civic_score", "type": "FLOAT", "mode": "NULLABLE"},
    {"name": "civic_id", "type": "FLOAT", "mode": "NULLABLE"},
    {"name": "id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "qual", "type": "STRING", "mode": "NULLABLE"},
    {"name": "as_filterstatus", "type": "STRING", "mode": "NULLABLE"},
    {"name": "as_sb_table", "type": "STRING", "mode": "NULLABLE"},
    {"name": "as_uniq_alt_read_count", "type": "STRING", "mode": "NULLABLE"},
    {"name": "contq", "type": "STRING", "mode": "NULLABLE"},
    {"name": "ecnt", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_hugosymbol", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_ncbibuild", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_start", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_end", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_variantclassification", "type": "STRING", "mode": "NULLABLE"},
    {
        "name": "gencode_34_secondaryvariantclassification",
        "type": "STRING",
        "mode": "NULLABLE",
    },
    {"name": "gencode_34_varianttype", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_refallele", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_tumorseqallele1", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_tumorseqallele2", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_genomechange", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_annotationtranscript", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_transcriptstrand", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_transcriptexon", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_transcriptpos", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_cdnachange", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_codonchange", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_proteinchange", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gc_content", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_referencecontext", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_34_othertranscripts", "type": "STRING", "mode": "NULLABLE"},
    {"name": "achilles_top_genes", "type": "STRING", "mode": "NULLABLE"},
    {"name": "cgc_name", "type": "STRING", "mode": "NULLABLE"},
    {"name": "cgc_geneid", "type": "STRING", "mode": "NULLABLE"},
    {"name": "cgc_chr", "type": "STRING", "mode": "NULLABLE"},
    {"name": "cgc_chr_band", "type": "STRING", "mode": "NULLABLE"},
    {"name": "cgc_cancer_somatic_mut", "type": "STRING", "mode": "NULLABLE"},
    {"name": "cgc_cancer_germline_mut", "type": "STRING", "mode": "NULLABLE"},
    {
        "name": "cgc_tumour_types___somatic_mutations_",
        "type": "STRING",
        "mode": "NULLABLE",
    },
    {
        "name": "ccgc_tumour_types__germline_mutations_",
        "type": "STRING",
        "mode": "NULLABLE",
    },
    {"name": "cgc_cancer_syndrome", "type": "STRING", "mode": "NULLABLE"},
    {"name": "cgc_tissue_type", "type": "STRING", "mode": "NULLABLE"},
    {"name": "cgc_cancer_molecular_genetics", "type": "STRING", "mode": "NULLABLE"},
    {"name": "cgc_mutation_type", "type": "STRING", "mode": "NULLABLE"},
    {"name": "cgc_translocation_partner", "type": "STRING", "mode": "NULLABLE"},
    {"name": "cgc_other_germline_mut", "type": "STRING", "mode": "NULLABLE"},
    {"name": "cgc_other_syndrome_disease", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_af_esp", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_af_exac", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_af_tgp", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_alleleid", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_clndisdb", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_clndisdbincl", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_clndn", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_clndnincl", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_clnhgvs", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_clnrevstat", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_clnsig", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_clnsigconf", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_clnsigincl", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_clnvc", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_clnvcso", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_clnvi", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_dbvarid", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_geneinfo", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_origin", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_rs", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_ssr", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clinvar_vcf_filter", "type": "STRING", "mode": "NULLABLE"},
    {"name": "cosmic_overlapping_mutations", "type": "STRING", "mode": "NULLABLE"},
    {"name": "cosmicfusion_fusion_genes", "type": "STRING", "mode": "NULLABLE"},
    {"name": "cosmicfusion_fusion_id", "type": "STRING", "mode": "NULLABLE"},
    {
        "name": "cosmictissue_total_alterations_in_gene",
        "type": "STRING",
        "mode": "NULLABLE",
    },
    {
        "name": "cosmictissue_tissue_types_affected",
        "type": "STRING",
        "mode": "NULLABLE",
    },
    {
        "name": "dnarepairgenes_activity_linked_to_omim",
        "type": "STRING",
        "mode": "NULLABLE",
    },
    {
        "name": "dnarepairgenes_chromosome_location_linked_to_ncbi_mapview",
        "type": "STRING",
        "mode": "NULLABLE",
    },
    {
        "name": "dnarepairgenes_accession_number_linked_to_ncbi_entrez",
        "type": "STRING",
        "mode": "NULLABLE",
    },
    {"name": "familial_cancer_genes_syndrome", "type": "STRING", "mode": "NULLABLE"},
    {"name": "familial_cancer_genes_synonym", "type": "STRING", "mode": "NULLABLE"},
    {"name": "familial_cancer_genes_reference", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_xhgnc_hgnc_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_xrefseq_mrna_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gencode_xrefseq_prot_acc", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_hgnc_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_name", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_status", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_locus_type", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_locus_group", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_previous_symbols", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_previous_name", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_synonyms", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_name_synonyms", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_chromosome", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_date_modified", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_date_symbol_changed", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_date_name_changed", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_accession_numbers", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_enzyme_ids", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_entrez_gene_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_ensembl_gene_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_pubmed_ids", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_refseq_ids", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_gene_family_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_family", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_ccds_ids", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_vega_id", "type": "STRING", "mode": "NULLABLE"},
    {
        "name": "hgnc_entrez_gene_id_supplied_by_ncbi_",
        "type": "STRING",
        "mode": "NULLABLE",
    },
    {"name": "hgnc_omim_id_supplied_by_omim_", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hgnc_refseq_supplied_by_ncbi_", "type": "STRING", "mode": "NULLABLE"},
    {
        "name": "hgnc_uniprot_id_supplied_by_uniprot_",
        "type": "STRING",
        "mode": "NULLABLE",
    },
    {
        "name": "hgnc_ensembl_id_supplied_by_ensembl_",
        "type": "STRING",
        "mode": "NULLABLE",
    },
    {"name": "hgnc_ucsc_id_supplied_by_ucsc_", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oreganno_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oreganno_values", "type": "STRING", "mode": "NULLABLE"},
    {"name": "simple_uniprot_uniprot_entry_name", "type": "STRING", "mode": "NULLABLE"},
    {"name": "simple_uniprot_drugbank", "type": "STRING", "mode": "NULLABLE"},
    {
        "name": "simple_uniprot_alt_uniprot_accessions",
        "type": "STRING",
        "mode": "NULLABLE",
    },
    {"name": "simple_uniprot_uniprot_accession", "type": "STRING", "mode": "NULLABLE"},
    {
        "name": "simple_uniprot_go_biological_process",
        "type": "STRING",
        "mode": "NULLABLE",
    },
    {
        "name": "simple_uniprot_go_cellular_component",
        "type": "STRING",
        "mode": "NULLABLE",
    },
    {
        "name": "simple_uniprot_go_molecular_function",
        "type": "STRING",
        "mode": "NULLABLE",
    },
    {"name": "dbsnp_asp", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_ass", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_caf", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_cda", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_cfl", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_common", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_dss", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_g5", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_g5a", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_geneinfo", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_gno", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_hd", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_int", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_kgphase1", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_kgphase3", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_lsd", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_mtp", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_mut", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_noc", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_nov", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_nsf", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_nsm", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_nsn", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_om", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_oth", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_pm", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_pmc", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_r3", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_r5", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_ref", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_rs", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_rspos", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_rv", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_s3d", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_sao", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_slo", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_ssr", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_syn", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_topmed", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_tpa", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_u3", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_u5", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_vc", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_vld", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_vp", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_wgt", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_wtd", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_dbsnpbuildid", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_filter", "type": "STRING", "mode": "NULLABLE"},
    {"name": "normal_barcode", "type": "STRING", "mode": "NULLABLE"},
    {"name": "tumor_barcode", "type": "STRING", "mode": "NULLABLE"},
    {"name": "center", "type": "STRING", "mode": "NULLABLE"},
    {"name": "source_", "type": "STRING", "mode": "NULLABLE"},
    {"name": "germq", "type": "STRING", "mode": "NULLABLE"},
    {"name": "mbq", "type": "STRING", "mode": "NULLABLE"},
    {"name": "mfrl", "type": "STRING", "mode": "NULLABLE"},
    {"name": "mmq", "type": "STRING", "mode": "NULLABLE"},
    {"name": "mpos", "type": "STRING", "mode": "NULLABLE"},
    {"name": "nalod", "type": "STRING", "mode": "NULLABLE"},
    {"name": "ncount", "type": "STRING", "mode": "NULLABLE"},
    {"name": "nlod", "type": "STRING", "mode": "NULLABLE"},
    {"name": "ocm", "type": "STRING", "mode": "NULLABLE"},
    {"name": "pon", "type": "STRING", "mode": "NULLABLE"},
    {"name": "popaf", "type": "STRING", "mode": "NULLABLE"},
    {"name": "roq", "type": "STRING", "mode": "NULLABLE"},
    {"name": "rpa", "type": "STRING", "mode": "NULLABLE"},
    {"name": "ru", "type": "STRING", "mode": "NULLABLE"},
    {"name": "seqq", "type": "STRING", "mode": "NULLABLE"},
    {"name": "str", "type": "STRING", "mode": "NULLABLE"},
    {"name": "strandq", "type": "STRING", "mode": "NULLABLE"},
    {"name": "strq", "type": "STRING", "mode": "NULLABLE"},
    {"name": "tlod", "type": "STRING", "mode": "NULLABLE"},
    {"name": "segdup", "type": "STRING", "mode": "NULLABLE"},
    {"name": "rm", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snpeff_allele", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snpeff_annotation", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snpeff_annotation_impact", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snpeff_gene_name", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snpeff_gene_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snpeff_feature_type", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snpeff_feature_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snpeff_transcript_biotype", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snpeff_rank", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snpeff_hgvs_c", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snpeff_hgvs_p", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snpeff_cdna_pos_cdna_length", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snpeff_cds_pos_cds_length", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snpeff_aa_pos_aa_length", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snpeff_distance", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snpeff_errors_warnings_info", "type": "STRING", "mode": "NULLABLE"},
    {"name": "lof_gene_name", "type": "STRING", "mode": "NULLABLE"},
    {"name": "lof_gene_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "lof_number_of_transcripts_in_gene", "type": "STRING", "mode": "NULLABLE"},
    {
        "name": "lof_percent_of_transcripts_affected",
        "type": "STRING",
        "mode": "NULLABLE",
    },
    {"name": "nmd", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbvarid", "type": "STRING", "mode": "NULLABLE"},
    {"name": "alleleid", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clnsig", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clnvcso", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clnrevstat", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dbsnp_rs_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clndnincl", "type": "STRING", "mode": "NULLABLE"},
    {"name": "origin", "type": "STRING", "mode": "NULLABLE"},
    {"name": "molecular_consequence", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clndn", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clnvc", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clnvi", "type": "STRING", "mode": "NULLABLE"},
    {"name": "af_exac", "type": "STRING", "mode": "NULLABLE"},
    {"name": "af_esp", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clnsigincl", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clndisdb", "type": "STRING", "mode": "NULLABLE"},
    {"name": "geneinfo", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clndisdbincl", "type": "STRING", "mode": "NULLABLE"},
    {"name": "af_tgp", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clnsigconf", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clnhgvs", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_allele", "type": "STRING", "mode": "NULLABLE"},
    {"name": "variant_info", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_impact", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hugo_symbol", "type": "STRING", "mode": "NULLABLE"},
    {"name": "ensembl_gene_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_feature_type", "type": "STRING", "mode": "NULLABLE"},
    {"name": "ensembl_feature_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_biotype", "type": "STRING", "mode": "NULLABLE"},
    {"name": "exon", "type": "STRING", "mode": "NULLABLE"},
    {"name": "intron", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dna_change", "type": "STRING", "mode": "NULLABLE"},
    {"name": "protein_change", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_cdna_position", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_cds_position", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_protein_position", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_amino_acids", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_codons", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_existing_variation", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_distance", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_strand", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_flags", "type": "STRING", "mode": "NULLABLE"},
    {"name": "variant_type", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_symbol_source", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_hgnc_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_canonical", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_mane", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_mane_select", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_mane_plus_clinical", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_tsl", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_appris", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_ccds", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_ensp", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_swissprot", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_trembl", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_uniparc", "type": "STRING", "mode": "NULLABLE"},
    {"name": "uniprot_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gene_pheno", "type": "STRING", "mode": "NULLABLE"},
    {"name": "sift", "type": "STRING", "mode": "NULLABLE"},
    {"name": "polyphen", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_domains", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_mirna", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_hgvs_offset", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_afr_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_amr_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_eas_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_eur_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_sas_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gnomade_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomade_afr_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomade_amr_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomade_asj_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomade_eas_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomade_fin_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomade_mid_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomade_nfe_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomade_remaining_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomade_sas_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gnomadg_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomadg_afr_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomadg_ami_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomadg_amr_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomadg_asj_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomadg_eas_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomadg_fin_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomadg_mid_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomadg_nfe_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomadg_remaining_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_gnomadg_sas_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_max_af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_max_af_pops", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_clin_sig", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_somatic", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_pheno", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_pubmed", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_motif_name", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_motif_pos", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_high_inf_pos", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_motif_score_change", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_transcription_factors", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_pli_gene_value", "type": "STRING", "mode": "NULLABLE"},
    {"name": "vep_loftool", "type": "STRING", "mode": "NULLABLE"},
    {"name": "am_class", "type": "STRING", "mode": "NULLABLE"},
    {"name": "am_pathogenicity", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_base__note", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_base__coding", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_base__hugo", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_base__transcript", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_base__so", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_base__cchange", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_base__achange", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_base__all_mappings", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_alfa__total_alt", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_alfa__total_freq", "type": "STRING", "mode": "NULLABLE"},
    {"name": "brca1_func_score", "type": "FLOAT", "mode": "NULLABLE"},
    {"name": "oc_brca1_func_assay__class", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_ccre_screen__acc_d", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_ccre_screen__acc_e", "type": "STRING", "mode": "NULLABLE"},
    {"name": "encode_group", "type": "STRING", "mode": "NULLABLE"},
    {"name": "encode_bound", "type": "STRING", "mode": "NULLABLE"},
    {"name": "cosmic_tier", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dida_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dida_name", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dida_effect", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dida_relation", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dida_fam", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dida_funct", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dida_dist", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dida_pub", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_dida__all", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gtex_gene", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_gtex__gtex_tissue", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gwas_disease", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_gwas_catalog__or_beta", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_gwas_catalog__pval", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gwas_pmid", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_gwas_catalog__init_samp", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_gwas_catalog__rep_samp", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_gwas_catalog__risk_allele", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_gwas_catalog__ci", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hess_driver", "type": "STRING", "mode": "NULLABLE"},
    {"name": "hess_signture", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_oncokb__protein_change", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oncokb_oncogenic", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oncokb_effect", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oncokb_hotspot", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_original_input__chrom", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_original_input__pos", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_original_input__ref_base", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_original_input__alt_base", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_provean__transcript", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_provean__uniprot", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_provean__score", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_provean__rankscore", "type": "STRING", "mode": "NULLABLE"},
    {"name": "provean_prediction", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_provean__all", "type": "STRING", "mode": "NULLABLE"},
    {"name": "pharmgkb_id", "type": "STRING", "mode": "NULLABLE"},
    {"name": "pharmgkb_chemicals", "type": "STRING", "mode": "NULLABLE"},
    {"name": "pharmgkb_pheno_cat", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_pharmgkb__drug_assoc", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_revel__transcript", "type": "STRING", "mode": "NULLABLE"},
    {"name": "revel_score", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_revel__rankscore", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oc_revel__all", "type": "STRING", "mode": "NULLABLE"},
    {"name": "spliceai_ds_ag", "type": "STRING", "mode": "NULLABLE"},
    {"name": "spliceai_ds_al", "type": "STRING", "mode": "NULLABLE"},
    {"name": "spliceai_ds_dg", "type": "STRING", "mode": "NULLABLE"},
    {"name": "spliceai_ds_dl", "type": "STRING", "mode": "NULLABLE"},
    {"name": "spliceai_dp_ag", "type": "STRING", "mode": "NULLABLE"},
    {"name": "spliceai_dp_al", "type": "STRING", "mode": "NULLABLE"},
    {"name": "spliceai_dp_dg", "type": "STRING", "mode": "NULLABLE"},
    {"name": "spliceai_dp_dl", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gt", "type": "STRING", "mode": "NULLABLE"},
    {"name": "ad", "type": "STRING", "mode": "NULLABLE"},
    {"name": "af", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dp", "type": "STRING", "mode": "NULLABLE"},
    {"name": "F1R2", "type": "STRING", "mode": "NULLABLE"},
    {"name": "F2R1", "type": "STRING", "mode": "NULLABLE"},
    {"name": "FAD", "type": "STRING", "mode": "NULLABLE"},
    {"name": "SB", "type": "STRING", "mode": "NULLABLE"},
    {"name": "ps", "type": "STRING", "mode": "NULLABLE"},
    {"name": "PASS", "type": "STRING", "mode": "NULLABLE"},
    {"name": "base_qual", "type": "STRING", "mode": "NULLABLE"},
    {"name": "clustered_events", "type": "STRING", "mode": "NULLABLE"},
    {"name": "fragment", "type": "STRING", "mode": "NULLABLE"},
    {"name": "germline", "type": "STRING", "mode": "NULLABLE"},
    {"name": "haplotype", "type": "STRING", "mode": "NULLABLE"},
    {"name": "map_qual", "type": "STRING", "mode": "NULLABLE"},
    {"name": "multiallelic", "type": "STRING", "mode": "NULLABLE"},
    {"name": "panel_of_normals", "type": "STRING", "mode": "NULLABLE"},
    {"name": "position", "type": "STRING", "mode": "NULLABLE"},
    {"name": "slippage", "type": "STRING", "mode": "NULLABLE"},
    {"name": "strand_bias", "type": "STRING", "mode": "NULLABLE"},
    {"name": "weak_evidence", "type": "STRING", "mode": "NULLABLE"},
    {"name": "PGT", "type": "STRING", "mode": "NULLABLE"},
    {"name": "PID", "type": "STRING", "mode": "NULLABLE"},
    {"name": "likely_lof", "type": "STRING", "mode": "NULLABLE"},
    {"name": "structural_relation", "type": "STRING", "mode": "NULLABLE"},
    {"name": "dna_repair", "type": "STRING", "mode": "NULLABLE"},
    {"name": "associated_with", "type": "STRING", "mode": "NULLABLE"},
    {"name": "lof", "type": "STRING", "mode": "NULLABLE"},
    {"name": "gof", "type": "STRING", "mode": "NULLABLE"},
    {"name": "likely_gof", "type": "STRING", "mode": "NULLABLE"},
    {"name": "driver", "type": "STRING", "mode": "NULLABLE"},
    {"name": "likely_driver", "type": "STRING", "mode": "NULLABLE"},
    {"name": "transcript_likely_lof", "type": "STRING", "mode": "NULLABLE"},
    {"name": "oncogene_high_impact", "type": "BOOLEAN", "mode": "NULLABLE"},
    {"name": "tumor_suppressor_high_impact", "type": "BOOLEAN", "mode": "NULLABLE"},
]


def upload_parquet_to_bq(table_id: str, gcs_uri: str):
    job_config = bigquery.LoadJobConfig(
        source_format=bigquery.SourceFormat.PARQUET,
        schema=schema,
        write_disposition=bigquery.WriteDisposition.WRITE_APPEND,
        column_name_character_map="V2",
        clustering_fields=["chrom", "pos"],
    )

    load_job = bq_client.load_table_from_uri(gcs_uri, table_id, job_config=job_config)
    load_job.result()
    print(f"Loaded {load_job.output_rows} rows into {table_id}")


with ThreadPoolExecutor(max_workers=4) as executor:
    futures = []

    for sample_id, r in eval_samples["wgs_cn_full_annotated_parquet"].items():
        table_name = sample_id.replace("-", "_")
        table_id = f"{bq_client.project}.mut_eval.{table_name}"

        try:
            bq_client.get_table(table_id)
            print(f"Table {table_id} already exists. Skipping upload.")
            continue
        except NotFound:
            pass

        for f in r["items"]:
            futures.append(
                executor.submit(upload_parquet_to_bq, table_id=table_id, gcs_uri=f)
            )

    for future in as_completed(futures):
        try:
            future.result()
        except Exception as e:
            print(f"Error: {e}")
